### ISSUE TITLE
Support for Render PHP File Mode in FrontEnd

### ISSUE THREAD

**Issue by noelboss** [kongondo/FieldtypeRuntimeMarkup#2]
Would be awesome if the "Render PHP File Mode" would work for the Frontend as well :)

https://processwire.com/talk/topic/10804-module-runtimemarkup-fieldtype-inputfield/?do=findComment&comment=168305

Thanks Kogondo! Great Module!

**Comment by kongondo** [comment]
Done in the [latest commit](https://github.com/kongondo/FieldtypeRuntimeMarkup/commit/98260d092ecd3cf10cad216a25c5cfc9b300086f)

Thanks for the suggestion.
